mod integer;

// use crate::ssl::*;

pub use integer::*;

// #[repr(u32)]
// pub enum Asn1Type {
//     EOC = V_ASN1_EOC,
//     BOOLEAN = V_ASN1_BOOLEAN,
//     INTEGER = V_ASN1_INTEGER,
//     BIT_STRING = V_ASN1_BIT_STRING,
//     OCTET_STRING = V_ASN1_OCTET_STRING,
//     NULL = V_ASN1_NULL,
//     OBJECT = V_ASN1_OBJECT,
//     OBJECT_DESCRIPTOR = V_ASN1_OBJECT_DESCRIPTOR,
//     EXTERNAL = V_ASN1_EXTERNAL,
//     REAL = V_ASN1_REAL,
//     ENUMERATED = V_ASN1_ENUMERATED,
//     UTF8STRING = V_ASN1_UTF8STRING,
//     SEQUENCE = V_ASN1_SEQUENCE,
//     SET = V_ASN1_SET,
//     NUMERICSTRING = V_ASN1_NUMERICSTRING,
//     PRINTABLESTRING = V_ASN1_PRINTABLESTRING,
//     T61STRING = V_ASN1_T61STRING,
//     TELETEXSTRING = V_ASN1_TELETEXSTRING,
//     VIDEOTEXSTRING = V_ASN1_VIDEOTEXSTRING,
//     IA5STRING = V_ASN1_IA5STRING,
//     UTCTIME = V_ASN1_UTCTIME,
//     GENERALIZEDTIME = V_ASN1_GENERALIZEDTIME,
//     GRAPHICSTRING = V_ASN1_GRAPHICSTRING,
//     ISO64STRING = V_ASN1_ISO64STRING,
//     VISIBLESTRING = V_ASN1_VISIBLESTRING,
//     GENERALSTRING = V_ASN1_GENERALSTRING,
//     UNIVERSALSTRING = V_ASN1_UNIVERSALSTRING,
//     BMPSTRING = V_ASN1_BMPSTRING,
// }
